.TH cfengine 8 "Maintenance Commands" HiOslo
.SH NAME
cfengine \- network configuration engine
.SH SYNOPSIS

/usr/local/sbin/cfenvd


.SH DESCRIPTION
.B cfengine
is a language based system specifically designed
for testing and configuring unix\-like systems attached to
a TCP/IP network. Cfenvd is part of the anomaly detection
subsystem for cfagent. It is a "plug'n'play" module
that provides machine learning support to the agent.
Cfenvd requires no configuration. It is completely optional.
If it is run, cfagent can extract useful data from it; if
it is not run cfagent continues as usual.

.PP
It is part of the on-going research in anomaly detection
using cfengine.


.SH AUTHOR
Mark Burgess, Oslo University College
.SH INFORMATION
http://www.cfengine.org

