.TH cfengine 8 "Maintenance Commands" HiOslo
.SH NAME
cfengine \- network configuration engine
.SH SYNOPSIS

/usr/local/sbin/cfkey


.SH DESCRIPTION
.B cfengine
is a language based system specifically designed
for testing and configuring unix\-like systems attached to
a TCP/IP network. The command generates a pair of public-private
keys for remote authentication during cfrun or cfagent and 
the server cfservd.

.SH AUTHOR
Mark Burgess, Oslo University College
.SH INFORMATION
http://www.cfengine.org

